import { createFileRoute } from "@tanstack/react-router";
import { z } from "zod";

const AttachmentSchema=z.object({name:z.string().max(180),type:z.string().max(100),dataUrl:z.string().max(28_000_000).optional(),text:z.string().max(80_000).optional()});
const BodySchema=z.object({locale:z.enum(["pt","en","es","fr","de"]).default("pt"),localTime:z.string().max(120).optional(),messages:z.array(z.object({role:z.enum(["user","assistant"]),content:z.string().max(80_000),attachments:z.array(AttachmentSchema).max(6).optional()})).min(1).max(60)});
const languageNames={pt:"Portuguese",en:"English",es:"Spanish",fr:"French",de:"German"} as const;
function systemPrompt(locale:keyof typeof languageNames,localTime:string){return `You are Lyrem 4 Pro. Never identify as any other name, model, provider, or company. Be warm, direct, creative, trustworthy and concise. Reply in ${languageNames[locale]}, unless the user clearly requests another language. Use excellent Markdown when useful. The user's current local date and time is ${localTime}. Use it for dates and deadlines. You may receive extracted file text or images. Never claim you analysed a video: for MP4 attachments, explain that you can use its filename and user description only. If asked for a downloadable file, provide the complete content in a fenced code block with a suggested filename. For executable requests, provide source code only and never claim to have created a binary. When current information is supplied by web search, cite links. For image creation requests, return exactly one Markdown image using https://image.pollinations.ai/prompt/ with an English URL-encoded prompt, width=1280, height=1280, nologo=true, enhance=true and a random seed. For video or animation requests, include ![short description](lyrem-video:URL_ENCODED_ENGLISH_PROMPT).`}
function userContent(message:z.infer<typeof BodySchema>["messages"][number]){const parts:Array<Record<string,unknown>>=[];if(message.content)parts.push({type:"text",text:message.content});for(const file of message.attachments??[]){if(file.type.startsWith("image/")&&file.dataUrl)parts.push({type:"image_url",image_url:{url:file.dataUrl}});else if(file.text)parts.push({type:"text",text:`\n--- Attached file: ${file.name} (${file.type}) ---\n${file.text}`});else parts.push({type:"text",text:`\n[Attached file: ${file.name} (${file.type}). Binary contents are not directly readable.]`});}return parts.length===1&&parts[0]?.["type"]==="text"?String(parts[0]["text"]):parts;}
function requestBody(body:z.infer<typeof BodySchema>,model:string,webPlugin:boolean){const messages=[{role:"system",content:systemPrompt(body.locale,body.localTime??new Date().toISOString())},...body.messages.map(m=>({role:m.role,content:m.role==="user"?userContent(m):m.content}))];return webPlugin?{model,stream:true,plugins:[{id:"web"}],messages}:{model,stream:true,temperature:0.7,max_tokens:8000,messages};}
async function callProvider(url:string,key:string,model:string,body:z.infer<typeof BodySchema>,extra:Record<string,string>={},webPlugin=true){return fetch(url,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key.trim()}`,...extra},body:JSON.stringify(requestBody(body,model,webPlugin))});}
export const Route=createFileRoute("/api/chat")({server:{handlers:{POST:async({request})=>{let body:z.infer<typeof BodySchema>;try{body=BodySchema.parse(await request.json());}catch{return Response.json({error:"invalid_request"},{status:400});}const groqKey=process.env["GROQ_API_KEY"]?.trim();const gatewayKey=process.env["LOVABLE_API_KEY"]?.trim();const fallbackKey=process.env["OPENROUTER_API_KEY"]?.trim();const hasImage=body.messages.some(m=>(m.attachments??[]).some(f=>f.type.startsWith("image/")&&f.dataUrl));let upstream:Response|undefined;
if(groqKey){const groqModel=hasImage?"meta-llama/llama-4-scout-17b-16e-instruct":"llama-3.3-70b-versatile";try{upstream=await callProvider("https://api.groq.com/openai/v1/chat/completions",groqKey,groqModel,body,{},false);}catch(error){console.error("Groq transport failure",error);}}
if((!upstream||upstream.status===429||upstream.status>=500||upstream.status===402||upstream.status===400)&&gatewayKey){try{upstream=await callProvider("https://ai.gateway.lovable.dev/v1/chat/completions",gatewayKey,"openai/gpt-6-astra",body,{},false);}catch(error){console.error("Primary AI transport failure",error);}}
if((!upstream||upstream.status===429||upstream.status>=500||upstream.status===402)&&fallbackKey){try{upstream=await callProvider("https://openrouter.ai/api/v1/chat/completions",fallbackKey,"openai/gpt-4o-mini",body,{"HTTP-Referer":"https://lyrem.lovable.app","X-Title":"Lyrem AI"});}catch(error){console.error("Fallback AI transport failure",error);}}
if(!upstream?.ok||!upstream.body){console.error("AI unavailable",upstream?.status);return Response.json({error:"temporarily_unavailable"},{status:503});}
return new Response(upstream.body,{headers:{"Content-Type":"text/event-stream; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}});}}}});
